### ISSUE TITLE
请问一下，您在体验网站gradio上部署的模型，大概训练了多少张印章图片呢

### ISSUE THREAD

**Issue by 0sensen0** [Gmgge/ImageAnalysisService#16]
请问一下，您在体验网站gradio上部署的模型，大概训练了多少张印章图片呢

**Comment by Gmgge** [comment]
演示的模型有印章检测和印章识别，你这边想要问哪个呢？

**Comment by 0sensen0** [comment]
想了解的是印章识别，印章检测顺便也了解一下

**Comment by Gmgge** [comment]
1.印章识别10w+（生成的占比很大）
2.印章检测1000+

**Comment by 0sensen0** [comment]
印章生成的工具，方法可以说一下吗

**Comment by Gmgge** [comment]
> 印章生成的工具，方法可以说一下吗

 可以参考rapidocr中的[文档](https://rapidai.github.io/RapidOCRDocs/blog/2022/10/01/inference-summary/?h=%E5%8D%B0%E7%AB%A0#ocr_2)说明
