### ISSUE TITLE
大佬，我直接运行你的项目，无识别你实例的图片

### ISSUE THREAD

**Issue by 0sensen0** [Gmgge/ImageAnalysisService#17]
![image](https://github.com/user-attachments/assets/5ac19777-e71e-4c6c-9315-12f3b0c4ee6b)
![image](https://github.com/user-attachments/assets/6f6dc78f-81cd-4b75-91e5-8b3ef70b9393)
![image](https://github.com/user-attachments/assets/7ff5be25-3a27-4ec0-9214-f8f0606f7b3e)

**Comment by Gmgge** [comment]
emmm 你缺少ocr模型，请关注下paddleocr、rapidocr。
